In [1]:
from extract import extract_data
from validate import validate_data
from transform import transform_data
from load import load_data

In [2]:
df = extract_data()

df.head()

Data extracted successfully
Rows: 31
Columns: 14

,patient_id,age,gender,doctor,department,appointment_time,consultation_start_time,glucose,cholesterol,heart_rate,spo2,temperature,diagnosis,treatment
0,P001,45,Male,Dr. Rao,Cardiology,2026-09-01 09:00,2026-09-01 09:25,112 mg/dL,188 mg/dL,82 bpm,98%,36.7 C,Hypertension,Medication
1,P002,32,Female,Dr. Priya,General Medicine,2026-09-01 09:15,2026-09-01 09:35,96 mg/dL,165 mg/dL,76 bpm,99%,36.5 C,Fever,Antipyretic
2,P003,67,Male,Dr. Kumar,Cardiology,2026-09-01 10:00,2026-09-01 10:48,145 mg/dL,220 mg/dL,91 bpm,95%,37.1 C,Diabetes,Insulin
3,P004,28,Female,Dr. Anitha,Dermatology,2026-09-01 10:30,2026-09-01 10:45,89 mg/dL,154 mg/dL,72 bpm,99%,36.4 C,Skin Allergy,Cream
4,P005,54,Male,Dr. Rao,Cardiology,2026-09-01 11:00,2026-09-01 11:42,130 mg/dL,205 mg/dL,88 bpm,96%,36.9 C,Hypertension,Medication

In [3]:
df.info()
df.shape
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   patient_id               31 non-null     str
 1   age                      31 non-null     int64
 2   gender                   31 non-null     str
 3   doctor                   31 non-null     str
 4   department               31 non-null     str
 5   appointment_time         31 non-null     str
 6   consultation_start_time  31 non-null     str
 7   glucose                  30 non-null     str
 8   cholesterol              31 non-null     str
 9   heart_rate               31 non-null     str
 10  spo2                     30 non-null     str
 11  temperature              31 non-null     str
 12  diagnosis                31 non-null     str
 13  treatment                31 non-null     str
dtypes: int64(1), str(13)
memory usage: 3.5 KB

patient_id                 0
age                        0
gender                     0
doctor                     0
department                 0
appointment_time           0
consultation_start_time    0
glucose                    1
cholesterol                0
heart_rate                 0
spo2                       1
temperature                0
diagnosis                  0
treatment                  0
dtype: int64

In [4]:
df = validate_data(df)

--- DATA VALIDATION ---

Missing values:
patient_id                 0
age                        0
gender                     0
doctor                     0
department                 0
appointment_time           0
consultation_start_time    0
glucose                    1
cholesterol                0
heart_rate                 0
spo2                       1
temperature                0
diagnosis                  0
treatment                  0
dtype: int64

Duplicate records: 1
Invalid age records: 1

Validation completed

In [5]:
df = transform_data(df)

df.head()

--- DATA TRANSFORMATION ---
Transformation completed

,patient_id,age,gender,doctor,department,appointment_time,consultation_start_time,glucose,cholesterol,heart_rate,spo2,temperature,diagnosis,treatment,waiting_time
0,P001,45.0,Male,Dr. Rao,Cardiology,2026-09-01 09:00:00,2026-09-01 09:25:00,112.0,188,82,98.0,36.7,Hypertension,Medication,25.0
1,P002,32.0,Female,Dr. Priya,General Medicine,2026-09-01 09:15:00,2026-09-01 09:35:00,96.0,165,76,99.0,36.5,Fever,Antipyretic,20.0
2,P003,67.0,Male,Dr. Kumar,Cardiology,2026-09-01 10:00:00,2026-09-01 10:48:00,145.0,220,91,95.0,37.1,Diabetes,Insulin,48.0
3,P004,28.0,Female,Dr. Anitha,Dermatology,2026-09-01 10:30:00,2026-09-01 10:45:00,89.0,154,72,99.0,36.4,Skin Allergy,Cream,15.0
4,P005,54.0,Male,Dr. Rao,Cardiology,2026-09-01 11:00:00,2026-09-01 11:42:00,130.0,205,88,96.0,36.9,Hypertension,Medication,42.0

In [6]:
load_data(df)

--- LOADING DATA ---

Data loaded successfully into MySQL

In [7]:
print("Hospital ETL Pipeline completed successfully!")

Hospital ETL Pipeline completed successfully!